image:
  registry: ea2p3demotsbacrgtdsm0nptbeqhdku.azurecr.io
  tag: 1.5.0-EA2
spec:
  components:
    gitops:
      enabled: true
      reconcileInterval: 600s
    internalCertProvider:
      certManager:
        managed: INTERNAL
    xcp:
      centralAuthMode: JWT
  hub: ea2p3demotsbacrgtdsm0nptbeqhdku.azurecr.io
  managementPlane:
    clusterName: ea2p3d1
    host: ea2p3demo.cx.tetrate.info
    port: 8443
    selfSigned: true
  meshExpansion: {}
  telemetryStore:
    elastic:
      host: 52.151.237.163
      port: 9200
      protocol: https
      selfSigned: true
      version: 7
