image:
  registry: ea1p4demotsbacrnzlo3rxfif4hdrhd.azurecr.io
  tag: 1.5.0-EA1
spec:
  components:
    gitops:
      enabled: true
      reconcileInterval: 600s
    internalCertProvider:
      certManager:
        managed: INTERNAL
    xcp:
      centralAuthMode: JWT
  hub: ea1p4demotsbacrnzlo3rxfif4hdrhd.azurecr.io
  managementPlane:
    clusterName: ea1p4d2
    host: ea1p4demo.cx.tetrate.info
    port: 8443
    selfSigned: true
  meshExpansion: {}
  telemetryStore:
    elastic:
      host: 20.185.9.61
      port: 9200
      protocol: https
      selfSigned: true
      version: 7
