image:
  registry: ea2p3demotsbacrgtdsm0nptbeqhdku.azurecr.io
  tag: 1.5.0-EA2
spec:
  components:
    internalCertProvider:
      certManager:
        managed: EXTERNAL
    xcp:
      centralAuthModes:
        jwt: true
  hub: ea2p3demotsbacrgtdsm0nptbeqhdku.azurecr.io
  organization: tetrate
  telemetryStore:
    elastic:
      host: 52.151.237.163
      port: 9200
      protocol: https
      selfSigned: true
      version: 7
