apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: dev
  name: bookinfo-ws
spec:
  namespaceSelector:
    names:
      - "gke-us-east1-01/bookinfo"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: dev
  workspace: bookinfo-ws
  name: bookinfo-gw
spec:
  description: bookinfo-gw
  displayName: bookinfo-gw
  namespaceSelector:
    names:
      - "gke-us-east1-01/bookinfo"
  configMode: DIRECT
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
Metadata:
  organization: tetrate
  tenant: dev
  workspace: bookinfo-ws
  name: bookinfo-security
spec:
  description: bookinfo-security
  displayName: bookinfo-security
  namespaceSelector:
    names:
      - "gke-us-east1-01/bookinfo"
  configMode: DIRECT
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
Metadata:
  organization: tetrate
  tenant: dev
  workspace: bookinfo-ws
  name: bookinfo-traffic
spec:
  description: bookinfo-traffic
  displayName: bookinfo-traffic
  namespaceSelector:
    names:
      - "gke-us-east1-01/bookinfo"
  configMode: DIRECT
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: bookinfo-ws
    tsb.tetrate.io/gatewayGroup: bookinfo-gw
  name: bookinfo-direct-gw
  namespace: bookinfo
spec:
  selector:
    app: bookinfo-gw
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "productpage.tetrate.int"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: bookinfo-ws
    tsb.tetrate.io/gatewayGroup: bookinfo-gw
  name: bookinfo-direct-vs
  namespace: bookinfo
spec:
  hosts: 
  - productpage.tetrate.int
  gateways:
  - bookinfo/bookinfo-direct-gw
  http:
    - route:
        - destination:
            host: "productpage.bookinfo.svc.cluster.local"
            port:
              number: 9080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: bookinfo-ws
    tsb.tetrate.io/trafficGroup: bookinfo-traffic
  name: bookinfo-reviews-vs
  namespace: bookinfo
spec:
  hosts: 
  - reviews.bookinfo.svc.cluster.local
  http:
    - route:
        - destination:
            host: reviews.bookinfo.svc.cluster.local
            subset: v2
          weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: bookinfo-ws
    tsb.tetrate.io/trafficGroup: bookinfo-traffic
  name: reviews-dr
  namespace: bookinfo
spec:
  host: reviews.bookinfo.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3