---
apiVersion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  displayName: lob1-azure-platform-ws
  name: lob1-azure-platform-ws
  organization: tetrate
  tenant: dev
spec:
  displayName: lob1-azure-platform-ws
  namespaceSelector:
    names:
    - aks-r152d3-eastus-0/tier1-gw-lob1
  privileged: false
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  displayName: lob1-azure-platform-gg
  name: lob1-azure-platform-gg
  organization: tetrate
  tenant: dev
  workspace: lob1-azure-platform-ws
spec:
  configMode: BRIDGED
  displayName: lob1-azure-platform-gg
  namespaceSelector:
    names:
    - aks-r152d3-eastus-0/tier1-gw-lob1
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  organization: tetrate
  tenant: dev
  name: tier1httpbinspgw
  group: lob1-azure-platform-gg
  workspace: lob1-azure-platform-ws
spec:
  workloadSelector:
    namespace: tier1-gw-lob1
    labels:
      app: tier1-gw-lob1
  externalServers:
  - hostname: httpbin-spring-gateway.gcp.cx.tetrate.info
    name: tier1httpbinspgw
    port: 443
    clusters:
    - name: gke-r152d3-us-west1-0
      weight: 100
    tls:
#to be switched to MUTUAL, to setup the MTLS with APIM
      mode: SIMPLE
      secretName: apim-facing-secret  