apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "chart.fullname" . }}-tier1-gw-lob1-httpbin-spring-gateway
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    tsb.tetrate.io/gatewayGroup: lob1-openshift-platform-gg
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: lob1-openshift-platform-ws
spec:
  selector:
    app: tier1-gw-lob1
  servers:
  - hosts:
    - httpbin-spring-gateway.gcp.cx.tetrate.info
    port:
      name: mtls-multicluster
      number: 15443
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL