apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}-tier1-vs-lob1-httpbin-spring-gateway
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    tsb.tetrate.io/gatewayGroup: lob1-openshift-platform-gg
    tsb.tetrate.io/organization: partners
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: lob1-openshift-platform-ws
spec:
  gateways:
  - tier1-gw-lob1/tier1-gw-lob1-httpbin-spring-gateway
  hosts:
  - httpbin-spring-gateway.gcp.cx.tetrate.info
  http:
  - match:
    - port: 15443
    route:
    - destination:
        host: httpbin-spring-gateway.gcp.cx.tetrate.info
        port:
          number: 443
        subset: httpbin-spring-gateway-se-subset