---
apiVersion: v1
kind: Namespace
metadata:
  name: tier1-direct
---
apiVersion: install.tetrate.io/v1alpha1
kind: Tier1Gateway
metadata:
  name: tier1-direct
  namespace: tier1-direct
spec:
  kubeSpec:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "false"
