image:
  registry: r150helm0tsbacrahbiwkvvrb9u6wii.azurecr.io
  tag: 1.5.0
secrets:
  tsb:
    adminPassword: Tetrate123
    cert: |-
      -----BEGIN CERTIFICATE-----
      MIIFojCCA4qgAwIBAgIUSSPa53EnzdjXRVxxCi6ZXu+n2v8wDQYJKoZIhvcNAQEL
      BQAwRzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRAwDgYDVQQKDAdFeGFtcGxl
      MRkwFwYDVQQDDBBTZWxmU2lnbmVkUm9vdENBMB4XDTIyMDgwMjE4MTMwNFoXDTIz
      MDgwMjE4MTMwNFowTDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRAwDgYDVQQK
      DAdFeGFtcGxlMR4wHAYDVQQDDBVFeGFtcGxlIFRTQiBFbnZveSBHVUkwggIiMA0G
      CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDqdZvrYtTmTgMUbg5OzBjCrlWaLZYs
      7hJ1yLwB5xWBqaL7bHeryX0ovLmz/4DFKcve7CPfq55gG66CUuWvun1kpRmL3tGZ
      iGibE4gWF447l+tPfPnddS7o2FeXevRk2gkzGq9hqtTIa95fpbCxErDJJeDlR28k
      2BD6L22TOqok6ryU9sJte2EyE4nQP07npVVgNc9z56fyxKbG0Pu4jtllWMk2XJ9H
      ys4vE8yWySL5udwSBWt/VeJXVeX0Nricw5oRxOOqeaWUkb80fZGIAz+zxVeHbfrL
      3kYLSN9WTVIthpXQKADD0DClcGEBVXcH3QA/fwzMCgzYXpo+Gz5YihTsTWld/54H
      BxolRNl3kZqus+razzWvcT1gg7ogMtgrUQgI2TSVrHr2J2wvowIt57IcIfmNBeup
      1QsZZ1OrkVRAT03PLfoVKHCJjZHz6Lb00uqX5WTDpBOtjTTIat95Px238jKkqNgc
      YM8EzXmQCtErvse763z0NilaBPcrNc5+Eqc9AhQBC5d50dJeFWqE4sTmvqNQ0vZx
      BAPjyKxmoFSeN0qrXNXyK7nGJW/BNvct0eism//OX7TPzVcxmLWnyMyTeENx0YJu
      R443L6+/RI4rW5o9RtTYGxXBgiVnrP87f89nPzgkkHqFsag2CzK7k3szULLSd/X1
      ajzSugHiQrtpcwIDAQABo4GAMH4wHQYDVR0OBBYEFBU2Ha/NunhjouH1w/rX7D5R
      uLWkMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
      BwMBBggrBgEFBQcDAjAjBgNVHREEHDAaghhyMTUwaGVsbS5jeC50ZXRyYXRlLmlu
      Zm8wDQYJKoZIhvcNAQELBQADggIBAFNvK53WrwaYIitHFsXs8PuoQnJ0lKx+j8W7
      FtEgJzyjsBRnk84IXC7ql05/z5lc+m47EJmhCaPQGdHnBmCHM43c9Wnt4MNfZ5rs
      Mlnj5jVWwro/NOCFGcZShdCaiGeAt/W7lnjFtxW5IC5TNozmYwI/h+5zpESeiyZR
      HiDyOrbHUmFrS5SKPm3wcKATwxyzCu1kKWrF+I4L2MD58qhQkaaVbSYuYlrSmQbi
      OLvmPyMnzX+Jt8a/veUoaQW6BlhI04HNrPjzhDmIAaBwkXC5VUj5ORp7YunHbsiP
      dC8GOvnZsl32h4KO9KtmQ3EmuHxus2xLjOO+b8wvHGRyhQivblX8b6n9XlTlxz2H
      cLiatboKdhCxz96jr1JRi0TnH01WsrPBtzTMe16nD8JQoUGEBvrUYXGtv8HZQDd8
      ZyBabJyBpFCpQ6npyNX0YtlaF3YETaoq5uYtt47TY9zKXiqgqN4T1TFwmhCOaoPh
      V29t4reuN10f+1/c8dlVP/F24yBqMFdycOnGtFRoB+EbK9/1k1JZxa29/unkMppH
      vylORSgv1qBI8PGjiWOXI1PZD9AXbllPkLV/mjQVQMhaMcN0dACjG/H6nc+e8VSd
      bBrOsh7Gjneh0Evw+qt5Yyq5ICTLBfYmgWDExhVW1bTRIQ2nN++5iadCie61XK0r
      Vj7nAcxo
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKAIBAAKCAgEA6nWb62LU5k4DFG4OTswYwq5Vmi2WLO4Sdci8AecVgami+2x3
      q8l9KLy5s/+AxSnL3uwj36ueYBuuglLlr7p9ZKUZi97RmYhomxOIFheOO5frT3z5
      3XUu6NhXl3r0ZNoJMxqvYarUyGveX6WwsRKwySXg5UdvJNgQ+i9tkzqqJOq8lPbC
      bXthMhOJ0D9O56VVYDXPc+en8sSmxtD7uI7ZZVjJNlyfR8rOLxPMlski+bncEgVr
      f1XiV1Xl9Da4nMOaEcTjqnmllJG/NH2RiAM/s8VXh236y95GC0jfVk1SLYaV0CgA
      w9AwpXBhAVV3B90AP38MzAoM2F6aPhs+WIoU7E1pXf+eBwcaJUTZd5GarrPq2s81
      r3E9YIO6IDLYK1EICNk0lax69idsL6MCLeeyHCH5jQXrqdULGWdTq5FUQE9Nzy36
      FShwiY2R8+i29NLql+Vkw6QTrY00yGrfeT8dt/IypKjYHGDPBM15kArRK77Hu+t8
      9DYpWgT3KzXOfhKnPQIUAQuXedHSXhVqhOLE5r6jUNL2cQQD48isZqBUnjdKq1zV
      8iu5xiVvwTb3LdHorJv/zl+0z81XMZi1p8jMk3hDcdGCbkeONy+vv0SOK1uaPUbU
      2BsVwYIlZ6z/O3/PZz84JJB6hbGoNgsyu5N7M1Cy0nf19Wo80roB4kK7aXMCAwEA
      AQKCAgEAspM5WqM//NnWRq08gI+7HCykTnYCN95seQGXEOvs2YFW/aCz1Uf16B02
      Y/5rGcCn4vaArE+OpSzwUZrKDnpAH3QQbRQdGI9o/RR3RjxSvNkNBNHvjdk/DWIZ
      9OpVUqsu7pmYkw8GWlCuYrNUTMorlEkhbgBmiu12oNeW4diA1vVjBSKdG74pXXa8
      NLzDYHPw/wJ9K455wNI/JJbv4rYKpsJlHt6VAp1ZRUoTPZWc6g/BqoguRCIp7tMh
      /kvfeKcSpg4MST+1+d64f0ZUnf+7eTUJYcFGkBiPyPCMCrOBr+MeIBkX3AypwJhD
      ijyKGJcfJT2jhZTyC6qiWENvzQf+vjcw5vtqRwa6idy/7TOdSNFVIzaaMMgzk0w0
      J0kVLYk/TYWsOjijxLx6xEHyVmFV5ql73OWtsDqDqRFp9m+Z7vgkCN2bXrBW3frI
      u9eJKKkIXL5CcE4fxlNlumQF4mKUxWPx0z3keKXMe4R9M1RwIcLScJM/Xw0jQ8My
      99Y6f8KRlqfcfgcsZxZo7aHcHRax2CY7fefHu5pYCqiEQKirqPrEWp2GeEk+rkUM
      NIoieYcMy6QfmCnZ+3IuYMI2tq3v5G29h5UtB5SHnP7si2TYdYMSbuzaBsrQAqHv
      f2rutdjaWoDKpOlKPUeyVlsxhZXkBd6A9VkwyZtpYY6vtNlbyQECggEBAPu+LPBR
      WDG6VYVl3nNpDFLWxw7uwJC7YNynwyYdwhuTS1OlR/ncMflzZ+Oc0qVrQDgXaYNw
      C/ImUyaU/N4v3mogm87SS6n2U5tSR+jzGGNz2Kxby4EU1vNdSx8pAtVpKyX5vuAy
      lTY9WL3nVYxVtZe2r4cTmxrjYnGkXA18Io34WVQV3ZXbMxSkdY7Nm/qETT/Ait4i
      5tiasfEr2UVc7ErsyfHUDITQ/Xs+knkVEUKszVz7RJGtLcfTe3jMQZ5rC8gXuJax
      wxv83EdcLaK9zcjcH06D+0zbdUC09kSYaTI9xTLuBoxEGU4/ZQIKf9vMecIqqvtC
      unQN0AnWnYTLq+ECggEBAO5snINNaLB7Mf7KggVhD7+43fanWrBRR4QTrdRPnqg1
      qiar4XV/VMOl22WXPvibn/P2qVaRk/TNqCHVo41qBA0qE8qhJi4NfiDSugJTAo+A
      kHT2RHfXxsSdOByr8mEicjUTYXzJG4knyktOPpar7QoO4IDNxmzt9JaXfx/blsyz
      2Pvzul2zV0ecYOPx3ZbgfskRZuVkG7rEj5xNkVSV/yXXZrDahUGIOYlq9rRpHnWj
      8tpwcWKa5kr3lSJljExxO2Lxvi4s0NOlnZZH/KDe+vErxvOH91jUX+YEDuKIqpbY
      c8WR/b9e0t5gBpyYYcEcZXm8d4YF82f7iOS4eNKcn9MCggEAKYIj+sQO3LQyobo4
      QaNSit4rGEU5ryOWRwvKW6CQfud8hiA8i/BItS7YNGmJOglDH3yMw0VYUucK0tPC
      FgiijbEuv51hKHcbNgMNJFXg8ZUKZvEDzxbWkm4RkuO6OeILYUmatXDhtX3MAhQA
      wRDozkkrDASpkHdppf9JxldvgyUt5XVtgeYQuBid4Zv5WgcyjY5710C9+30WVgO6
      4Xr+4yPD8IHcRpIHGakpkZltrSa8/dXYaoS5hbdTJonXT/2qhaWTpBVPbG/3CjUi
      uTC+m53f85xDdVrCLJcp/Al9XvFccJdasQoRehtt1jZQ+rbuZJuQcbmA8N3OLbEb
      a+gBQQKCAQAKZb4lk7ifCaBShi5JYcQ4Di3P1diEm+bMgbcw7Q/0MfLroM9COn1N
      0uvQcFoUqWS+VOFpnwuev2E3qINrZVYr5MvcKE7r7zay472s4EXaUDb8gsjVmRlX
      9as+xNjbF493dRLpSDPlNVEDG7RrCbBaoe90boTatz3VW2H117Op1aX+xtA3ydxi
      iRVIm4GYVM3yosmj80uqR2wj2tYdpDTuR4h46e6pvvETZxC/KV5krvOmRwUK0cp9
      NnLQfzExHDcEx5oNlXK96BkJNrZzpYW4Arq4YBOPUiOkekTT6DXYQjQ6R3WTZOU5
      QWLIbXTF4SEjv+5Ob+//dt6vasQKGz51AoIBAHoxCnaV5NNb+siFCgWXARaqKCm8
      JR8R+wySogGLh4O6+Ou9+qdYw/28f+OMMZlDBY/wFuckP/GYr2asvR61UzVmM64m
      JD9zeY7IYPfTcs4of731AL39poIqW78GB35V2kaKrwQuOEYRSj7EWrwXImaaT07r
      AzVqiTyvIvTMCU88dha0Gs2vUcaBdt0JCxIQ5As1Y9vXe4xOFUqZm2F6zCdM6gNi
      /cuZ69vlCKm2pd1Y/lJIc67QyLeTatv2K8dLoLqwsGg3E9zda078z2kFbnh0JwpY
      wfzDHftf60k9Sw99j6AGzK0v9JLKku7NHulCN+aSXmPKD77tfs92Juv7YDQ=
      -----END RSA PRIVATE KEY-----
  xcp:
    autoGenerateCerts: false
    central:
      cert: |-
        -----BEGIN CERTIFICATE-----
        MIIFyjCCA7KgAwIBAgIUSSPa53EnzdjXRVxxCi6ZXu+n2wAwDQYJKoZIhvcNAQEL
        BQAwRzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRAwDgYDVQQKDAdFeGFtcGxl
        MRkwFwYDVQQDDBBTZWxmU2lnbmVkUm9vdENBMB4XDTIyMDgwMjE4MTMwNVoXDTIz
        MDgwMjE4MTMwNVowQjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRAwDgYDVQQK
        DAdFeGFtcGxlMRQwEgYDVQQDDAtYQ1AgQ2VudHJhbDCCAiIwDQYJKoZIhvcNAQEB
        BQADggIPADCCAgoCggIBAK0cL+8+pRXDWArl8QUU3XCrQ9MasGBH6bOpHksMgHSJ
        ZRgHCoZ9GuGSaNI1sjVOirY0UlrigryjzoHXa4w22UMgiy1BZWdIBhqZ8hfp4j4n
        Tm1VOGFWHoQxmCjcqi62OyFxK20OKsDHkoRc71FB5uaPydTt7ddL/eqwo2my7xsH
        BMdpG0YHcm0CqgbQctIE0LE0N24r+AnvPME8hIdEwbhSpBbPDjjBNy6DLUKIVWK5
        UHPTXY6mp6eTS5FAD59VqekZ2eA+F6llxLZFylKNrn+aUoLvFh9VxLL5yovxEbi2
        zvhyGIPhfEm7rLgeLFhr+YMzvqxD99fs0KxjcJz7vjxi5BIz1wRwSQV1UhDPURnx
        rzwnMFXMMHYSen95w62Re6CgZrtViC31N2Bdmv3D4zpeALbJjB8r0Mcx3sNfEoh4
        isAN3ceQIve9SRU2Z37A8vudh+11K/EnD6kC9aq4QPfzZujJ1V4MA8g+d6Q/u50c
        WxK95rJgYgpI0GpOTSNX3wLfoc+w0gnz7Hja2aOLP6FVNpCds4+ZilX5mu9FOMh6
        Q8P6J8knFGN2ktLM0GnQoMMqiDshXqLc4p26ovXh+3PeKfN1dcVAZDpy78aa+GR4
        5+Pp6aP+JEMcfTg03a0wnq8E4q0qgLqGe/K3CJbY9KkijYHeTBXUAscmK9YHohXV
        AgMBAAGjgbIwga8wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCBaAwHQYDVR0lBBYw
        FAYIKwYBBQUHAwEGCCsGAQUFBwMCMHMGA1UdEQRsMGqCDnhjcC50ZXRyYXRlLmlv
        hh9zcGlmZmU6Ly94Y3AudGV0cmF0ZS5pby9jZW50cmFsghhyMTUwaGVsbS5jeC50
        ZXRyYXRlLmluZm+CHXIxNTBoZWxtLmN4LnRldHJhdGUuaW5mbzo5NDQzMA0GCSqG
        SIb3DQEBCwUAA4ICAQBdpzV9YNDRLk66Zp90EuzoH5zblP0MwAoyWSLp42dvrC+9
        Of+kFJuxMgli6wz0op7fDFlghLfN5/I26vhc7HRvbRXs+IA6Fj6HrW5IVKLUlRLh
        qYw+x5Io/q+mPedrroOCmxvdOusWvZRaPXzsDaObhVQRkW7sicTg4YRVXWRmAO9Q
        ctn1h3n2kzKANlV6UiDhUeC8yKzvYP+bzBJuEZep4yboPCk5iOoOTSQIN1PYzCf5
        z/oIDxbnyH0TOCSMqPqK2aNotAtB2Jof6MiheX1jXgRm7zMilpRbOwJBBLmjAuCx
        AF5xOtA3qNDWdjDwKG0CrH1NUHY+O9+GkmZpJ3ayfph3yDKf8cJpVixvJc4ZVPWv
        Dl1pD13lUqjkxS4X46q73kzSrk7uVipe938/i5kIvioLUQhhULJkKt8BpZoPydiw
        VkLPdvo288YXS+kt7HXmkyKzESmn3WNwKx5WKpGkc+OpgxVvBFvZlNcXG42XcVhY
        cG65tcf0wbn0i3gT89zg5f4m2djBuPPRPUhaSJL7FlUOzPKfyamEaHyXDUG+qoxr
        Vd3ioEZxLn8EZD/Vmw6rX0J65tUnOaUWVnXAF7FiS5WTZAIegR64r+16YiHjyQBp
        PL+6nebObnRNlB6JAmNIimpB4MuAfM/D5qpaLyCMsu10vsMLBJwxogUcX6gWQA==
        -----END CERTIFICATE-----
      key: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKAIBAAKCAgEArRwv7z6lFcNYCuXxBRTdcKtD0xqwYEfps6keSwyAdIllGAcK
        hn0a4ZJo0jWyNU6KtjRSWuKCvKPOgddrjDbZQyCLLUFlZ0gGGpnyF+niPidObVU4
        YVYehDGYKNyqLrY7IXErbQ4qwMeShFzvUUHm5o/J1O3t10v96rCjabLvGwcEx2kb
        RgdybQKqBtBy0gTQsTQ3biv4Ce88wTyEh0TBuFKkFs8OOME3LoMtQohVYrlQc9Nd
        jqanp5NLkUAPn1Wp6RnZ4D4XqWXEtkXKUo2uf5pSgu8WH1XEsvnKi/ERuLbO+HIY
        g+F8SbusuB4sWGv5gzO+rEP31+zQrGNwnPu+PGLkEjPXBHBJBXVSEM9RGfGvPCcw
        VcwwdhJ6f3nDrZF7oKBmu1WILfU3YF2a/cPjOl4AtsmMHyvQxzHew18SiHiKwA3d
        x5Ai971JFTZnfsDy+52H7XUr8ScPqQL1qrhA9/Nm6MnVXgwDyD53pD+7nRxbEr3m
        smBiCkjQak5NI1ffAt+hz7DSCfPseNrZo4s/oVU2kJ2zj5mKVfma70U4yHpDw/on
        yScUY3aS0szQadCgwyqIOyFeotzinbqi9eH7c94p83V1xUBkOnLvxpr4ZHjn4+np
        o/4kQxx9ODTdrTCerwTirSqAuoZ78rcIltj0qSKNgd5MFdQCxyYr1geiFdUCAwEA
        AQKCAgBxPWoh7/Hf/aw/XNHAiDifNnmkw+Wy5ff73dqCL4hsM2CdSiXZekc2XicR
        s6yC8IEO1cU1zMzHB8TT7Q5eZ5bSMZy5mvjxigzsI95ZRFcKX34PSVsbWVGXGjY2
        LLtq2SxvIO/OZCEVgLfYvE6U8i5QjqjyED6wwvY0Kx6Ky1FcdcfrhlcgBUkWBFMj
        KAKkXiACe2zzNfII1aYBpkvvjMvIfs72WLYt7D7jv03BIxvv+9ekHRUrdttfZJxf
        RO+zRD9ky9NZvGSQHJGExrymKiaHNHVbT3lCQEHu7jZQOv9jvLpBjal5w+wg85L1
        0k8h/Gf5KsVFPSUI69JJorcNCiUTmhTbvJAKoAB/pMfn/OPD3fYzBUsSMb2t1yk5
        bMQ9lOdw5WhZAcav9l3eNZaej+lXVOoK07bt0jvS3r1w2KHJV/hy3C5qVQLM8UET
        44506FYd5jvYpbDqHdO/DfTrg+bopCbIqZZiZtas96T3u9TUX09AeT5gnDlKWqdb
        xYWH9p+U/dyotGWmQcKZajFopkMgy2TSY47wU1KbeyFSIU1ru1gpiU8ngeHmppf4
        W6zvRFrDZVAKuw1AWG4XGjE1b0H2u09cQXX9F6wuRX7WFRAuPuXMqM/5MhARlt9s
        EElxjnl4aMnAk/Qt+GJbo2Q/AscdMPuksU0BfhFZ/NpPBnm0wQKCAQEA04+Cmfv9
        6JGyFcls9/5lnNE8sn3v7Asbup31yE6ybnoXex1w8tdSSRDcTq7OkwQWlO0muNX6
        uG9MoFug+lfoyF9n5mR8F+kwbJlw7q45BuVRyn+p0UGUTz5lO1LafSbNM/qI+J6a
        3sV14YJtB5xxn+vR/6vBWy4rUyJncJgIbq7sCYsix9IAHGekKKhpcFv+Skt2lX0g
        mcuaQXqPheMHOn8F/6eDXP/xBu1i5sYLBi09BiopsDJyK0cySdX4ov/uUasqBRPI
        IAgWrtG+7W6lemy0F1xMc9msEdGIFC1UGzae8rOmzvhSrpRW0TNNXuuBZmTWzhUX
        f05oNEGAnUHPUQKCAQEA0XkJDQPwwI6h95SN6Mv/O4GYs/acwoXFCQPCsLZoV0SA
        Dt5BtVS3BpCBOyjmkctHBvMp2SevdsfXBreSW1mhZDbdPC5VLTTH4dOvKxCdAYr4
        y0bmIwmNbYuSv1eEZSZ6DbfDrL8MPEp5hYu/HJQKezZywCjuv2K1COjMD6yg+VNG
        Zt4IheiYxuImn/yN3ixeRFLhRxDO+EZ1XaGLvCkvIuEnnaRB48vX8OfNtiFUpk/p
        e1syFMoGIat5PqzIHyP+86aTsQQJkqUcT0rJxeA9cCP+ulijaBp/l6MycX8vtVCE
        qsakfO6tpU0UtOwNtvqprZh5BHDmP23tCIV1oGalRQKCAQAJYK4gVzwtB/BF6PTM
        lVk5t0iifNSauO9UuVXAuEROg1jxGx/7k7HRDU9GqZb8i0zY8x4pSUrgzAYwgX9E
        OYtW/mujmcaqZKrB1Zdc7RoYBSg3+qqzXN3PGWvxUj3fGE42RJ+3rYgd4dDU2yws
        DzI2LYTUeW+LtCM1fyvooMSW62gJEELNarCYkbuEFdr+oQVHk8rA25gLWSwQRPeB
        rsuOOz0v1OQMxkeP0Av3QMYSUwUGde39Im9PHcvL3BE2YHPW6Ohm6zaOvO0MeL2m
        1qW9JH5jHrNA22A2Nfx7MHsu7Z/kEDSPrhA0Lt0eTtDaKURGHqgq4GJ3QSl7T3/8
        +ILRAoIBAFFKUEndwptnftGOs/eo2vbj1zfXt4QB17Ik5HQhhaKAMdYTSJqvMov4
        nj4wJDJmGb1HtnDQZtaIvRidOs36nZg/dmG5dVKizgMEXFExFE0Z+m0gqYTlWx4s
        8RkSRI3gfbM/Ik+yoHPxTvGVhuf3R44DVkreV7CsBKddeHuIubuoJoUbG2GkH03n
        S6gAoambvEV1iHlEu5078qYQYCL4NJOrnu0dZniZjcaunnVUv/3+uxQlEu1gbTq5
        ycaZ1NvI41L4zQ4ADBr9ulvHIUCKQi13uo3kgh2PUv6s1ZGYExKhGasQhZr6IScq
        H6QKi1P8OMbmiehATApHhZot+LTzwKUCggEBAJv+Z5PKXXORSLrS9uDt3TdEnmTr
        aeOsFRQlSF5VowSVIKu7w4hFPyxTT6pxHF1ICB6uLK0y8Em2ae2xkMn8LtAhI/Cq
        lW6A5G8DJMvRJ/w1SGfPtVd4N+WdwjLnnM9Tk3rOS26ojYTRcB2ljPB3myGMP2L/
        0L9JX8UAm0Tt9Ly3KdawfKlsdB/whAlneGHs7bcGutdRZJYv/q6S2toSblVzsp3k
        1M0SjEv+qLnhKFNF4yj5AUX3OKRRg1I/hRqxVZZXA7nZ7D8PnMUshYCQvz9ecY7B
        Z7qosLVqWh+xcAfcpeejtmW8z98qhGl9MV3zrYumf6rOH0ZmJxb1lUWVlFw=
        -----END RSA PRIVATE KEY-----
    rootca: |-
      -----BEGIN CERTIFICATE-----
      MIIFXjCCA0agAwIBAgIUNbI+JjsvVOx+mVvzYP13IMLPtu0wDQYJKoZIhvcNAQEL
      BQAwRzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRAwDgYDVQQKDAdFeGFtcGxl
      MRkwFwYDVQQDDBBTZWxmU2lnbmVkUm9vdENBMB4XDTIyMDgwMjE4MTMwNFoXDTIz
      MDgwMjE4MTMwNFowRzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRAwDgYDVQQK
      DAdFeGFtcGxlMRkwFwYDVQQDDBBTZWxmU2lnbmVkUm9vdENBMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEAyyCikEo3CWCmUoOkqH+AAKS6mtG9J/iQ//tJ
      eqUssWIKbxcDNDjQ784CS7e0EmzA1nabNtvlpHZLy0B7Deta+vN8pRV8MRmADh1U
      Fge5/Sj8iGi8e5rkaWC8ZlX6imkMVGUWQEqgJcNz6NEuBBkttD9QM3KKM7i28h+S
      +8HqaIZwAqKKOoY3hzpfudaCKSoBlzE1v0SkVGLg2TvFqq1JqMQ1mYJdbbI30TPU
      qs9SWqwk9xfuwb+de3N5afUJcaxpmoJbmnnFEk6t62UQlYZmSTwnks9oTp2CWPUR
      tZhz/Yd0h6PojCswEAv5iqnfKscWlDF/iAfoUWgiwffqqfz/OlHkuTqEhLw63hx6
      lsm+3/UfBjfowr8R2xBn91d++2cz1tFmjeiacvfJgSWY9fR8jWJcTsfCxYdjNg9o
      vmuTg/1zmdGyoULt7RFOmhzx4T2cTPOmJuzLrxxfhxYz93+rKUHt2Vw81jYnNTQI
      u/61SSWSo7Xc30THCy+wqYQY/dqxK3ydnr3sIKsv6IFf8jP4IRhj6PUkHAshifyv
      eKv7BsAnEFKzqZlLpO+WchEv9bA6bRXRz1ca4UA7h/QeCxPX3f+2CxgLdtw1f351
      TZ7kTCWnmr/fht4AWreGdh0ond4vKRT/mn4JE15U4zBpaH4XdPpl2PiQTm2gIi5T
      a6VQDBUCAwEAAaNCMEAwHQYDVR0OBBYEFCMskxZfPp51Ypa2l0M17R8b4px+MA8G
      A1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgLkMA0GCSqGSIb3DQEBCwUAA4IC
      AQCBHJwToZ8jZwut+d1JSmoi8J2kPfvEobzYcYBzB2iqWnDe2lRpk4VWXCyIjgJx
      Ig0PvL6E9PR/hpnO9SSxI9NRm0znXq1bBdKKiiClP2Ku6vwl94gX4i89cTNxGeL6
      IdLn8E5SwukcEfoULY0bUz1e6a70oG2biWEYj5NLpn58u7TS4nLdai5hPHz3VP1M
      1F493Op9QhLf8oY3unEwcLcjE7U8pubwTddQBUXG96NYMcN7g0wLsoEQ1drm8ry8
      M7no8rRvEsxGoNK6FFvRUUv35d/wbmp0oB1r2mztVBAdbj3cMocY7BbBJVC/jLn/
      FEmotkzzUa17Gknyu8ZLfu4dXNthjXedKyaqAkNBS7082xPPJis4DDeRosDfZIYn
      PIjI5F/tZSGsaWvQ3ZetAj5fMnOUQ4UuCniASF6cXUISAwsJnLjsdCDEweklQO0O
      OngNcyDAARtpZ/272QzOx9NZKrZeE2KwEix0ihShBcMadQpQuBacQ/089U2xTxQk
      Nce0a9M1+rc9iK+7Z41vSlo58XmvEkbDBPJdh7bTzJX8iXfzNv4/pL7ebulXnvEU
      I/hFLZ7FSsw6n2RkGMZMYVDYl9lW8uszqpqW7kROGjXFjhcuWKnntole5nV2Rhxv
      dahjgWULwvjgZVKOD+oDp6ZDcKhY13BRecmL+FvoGzaHiQ==
      -----END CERTIFICATE-----
spec:
  hub: r150helm0tsbacrahbiwkvvrb9u6wii.azurecr.io
  organization: tetrate
